version: '3.1'

services:
  db:
    container_name: "$DB_CONTAINER_NAME"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_PASSWORD"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
    depends_on:
      - "db"

  server:
    container_name: "$SERVER_CONTAINER_NAME"
    restart: always
    ports:
      - $SERVER_PORT:8080
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env

volumes:
  mysql-data: